var gold = "#a37521";
var green = "#1C4436";
export var Gold = "bg-[" + gold + "]"
export var DarkGreen = `bg-darkgreen`
export var DarkGreenScroll = `bg-[${green}]/90`;
export var ButtonClr =  "border-5 hover:text-xl " + "border-[" + gold + "] "
export var LightYellow  = "bg-[#ebd698]";
export var Beige = "bg-[#bd9f68]";
export var Gray = "bg-[#95a3b2]";
export var LightPurple = "bg-[#c6caed]";
export var nHeight = "20"
export var navHeight = "h-" + nHeight
export var navSpacing = "pt-" + nHeight
export var GoldText = "text-[" + gold + "]"